const data = {

    candidates : [
        {
            _id: '1',
            name: 'Lukas Skywalker',
            category: 'Canino',
            image: '/images/p1.jpeg',
            age:'100 años',
            sponsor:'Obi-Wan Kenobi',
            sponsorNumber:'3003004444',
            genre: 'Macho',
            health: 'buena',
            sterilized: 'Si',
            description:'Un amigo de una galaxia muy muy lejana ha venido a rescatarte del malvado imperio galactico',
        },
        {
            _id: '2',
            name: 'Chewbacca',
            category: 'Canino',
            image: '/images/p2.jpeg',
            age:'60 años',
            sponsor:'Han Solo',
            sponsorNumber:'3003004445',
            genre: 'Macho',
            health: 'buena',
            sterilized: 'No',
            description:'Un amigo parte de la rebelion quien conoce la ubicación de la base secreta',
        }
    ],
    products: [
        {
            _id:'1',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p1.jpeg',
            price:'80000',
            countInStore: 12,
            brand: 'Super Tiernos',
            rating:1.5,
            numReviews:7,
            description:'Protegelos de la lluvia',
        },
        {
            _id:'2',
            name:'Capa impermeable para perros',
            category:'Perros',
            image: '/images/p2.jpeg',
            price:'100000',
            countInStore: 9,
            brand: 'Super Tiernos',
            rating:2.5,
            numReviews:8,
            description:'Protegelos de la lluvia. Talla grande',
        },
        {
            _id:'3',
            name:'Hueso grande y pequeño',
            category:'Perros',
            image: '/images/p3.jpeg',
            price:'15000',
            countInStore: 0,
            brand: 'Super Tiernos',
            rating:3.5,
            numReviews:9,
            description:'para sus dientes',
        },
        {
            _id:'4',
            name:'Pelota Gato',
            category:'Gatos',
            image: '/images/p4.jpeg',
            price:'18000',
            countInStore: 1,
            brand: 'Super Tiernos',
            rating:4.5,
            numReviews:10,
            description:'La mejor diversion Gatuna',
        },
        {
            _id:'5',
            name:'Juguete Mostacho',
            category:'Perros',
            image: '/images/p5.jpeg',
            price:'30000',
            countInStore: 2,
            brand: 'Super Tiernos',
            rating:5,
            numReviews:10,
            description:'Se diverte el y te ries tu',
        },
        {
            _id:'6',
            name:'Suplementos Perros',
            category:'Perros',
            image: '/images/p3.jpeg',
            price:'120000',
            countInStore: 20,
            brand: 'Super Tiernos',
            rating:5,
            numReviews:23,
            description:'Se diverte el y te ries tu',
        },
    ],
};
export default data;